# This file contains settings for code analysis and linting.
include: package:flutter/analysis_options.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_return: error
    unnecessary_getters_setters: warning

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - unnecessary_new
    - always_specify_types
    - prefer_single_quotes
    - type_annotate_public_apis
    - public_member_api_docs
    - lines_longer_than_80_chars
    - avoid_annotating_with_dynamic
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_this
    - avoid_function_literals_in_foreach_calls
    - prefer_typing_uninitialized_variables
    - prefer_mixin
    - prefer_collection_literals
    - avoid_redundant_argument_values
    - avoid_types_on_closure_parameters
    - prefer_adjacent_string_concatenation
    - unnecessary_lambdas
    - prefer_final_locals
    - prefer_const_literals_to_create_immutables
    - prefer_inlined_adds